export const FETCH_CRICKETERS_SUCCESS = 'FETCH_CRICKETERS_SUCCESS';
export const ADD_CRICKETER_SUCCESS = 'ADD_CRICKETER_SUCCESS';
export const DELETE_CRICKETER_SUCCESS = 'DELETE_CRICKETER_SUCCESS';
export const EDIT_CRICKETER_SUCCESS = 'EDIT_CRICKETER_SUCCESS';
export const API_FAILURE = 'API_FAILURE';